### ISSUE TITLE
Add Random Joke Generator via API

### ISSUE THREAD

**Issue by Kush-munot** [irshadmd/Awesome-CSS-Projects#100]
Hey I would like to Contribute to the project by making a jokes generator

Please Assign this to me

Thanks !!

Please also add Hackoctober Tags :)

**Comment by irshadmd** [comment]
go ahead 🚀

**Comment by Satyabrat-Ojha** [comment]
I also want to contribute can you please assign me too

**Comment by Satyabrat-Ojha** [comment]
I have completed it and made a PR - https://github.com/irshadmd/Awesome-CSS-Projects/pull/165
Please do check it out

**Comment by Kush-munot** [comment]
> I have completed it and made a PR - #165 Please do check it out

Hey This issue was assigned to me. So technically it is to be resolved by me. I am working on it. Please do not violate the code of conduct. It has been a day since assignment of the issue. Please find some other issue.
Thanks !!

**Comment by Kush-munot** [comment]
@irshadmd 
added the Joke Generator #187. This is my PR that I have contributed for the assigned Issue.

**Comment by irshadmd** [comment]
> 

good work
