### ISSUE TITLE
create a home page

### ISSUE THREAD

**Issue by irshadmd** [irshadmd/Awesome-CSS-Projects#11]
* Cards to preview all the projects present in [Awesome-CSS-Projects](https://github.com/irshadmd/Awesome-CSS-Projects)

**Comment by tanmay-S12** [comment]
Hey, I would like to work on it, But request you to pls elaborate a little more about the "Homepage". Do consider me to assign this issue.

**Comment by irshadmd** [comment]
Great @tanmay-S12
* The idea is that cards should be dynamic i.e: read all folders present in [Awesome-CSS-Projects](https://github.com/irshadmd/Awesome-CSS-Projects)
* On the card click open the respective project code

here is a kind of sudo design 😅, you can modify however you like
<img width="904" alt="Screenshot 2022-10-02 at 4 32 03 PM" src="https://user-images.githubusercontent.com/32608381/193450731-ef8b59fd-62ea-4fbb-b900-0ee6e19bede8.png">

**Comment by AnshikaAgrawal5501** [comment]
Hi @irshadmd,
I would like to work on this issue. Please assign me this issue.

**Comment by vivekkiranpatil** [comment]
@irshadmd I think I can do the same with bootstrap, will send pull request soon

**Comment by irshadmd** [comment]
@tanmay-S12 are you working on it? if not I'll assign this issue to @AnshikaAgrawal5501

**Comment by abhijain2003** [comment]
Hey, I wanted to work on this under hacktoberfest, just tell me can we make it using reactjs and you are talking about dynamic so, it should have a database to where I believe to add a button on home page to add new project but tell me how to persist data I mean which system you are using I am familiar with firebase, mongodb

**Comment by irshadmd** [comment]
@AnshikaAgrawal5501 assigning this to you

**Comment by AnshikaAgrawal5501** [comment]
> @AnshikaAgrawal5501 assigning this issue to you

Thanks! I will soon raise a PR with the complete work.
