### ISSUE TITLE
Random Dog image generator using HTML, CSS and javascript

### ISSUE THREAD

**Issue by rajutkarsh07** [irshadmd/Awesome-CSS-Projects#117]
I will make a page which will show random images of dog. By using API to fetch dog image

**Comment by irshadmd** [comment]
If you can do it with html css and js only

**Comment by rajutkarsh07** [comment]
If I make it using HTML CSS and js then will it be counted under hacktoberfest?

**Comment by rajutkarsh07** [comment]
I will make it using HTML CSS and js
Assign this to me
Thanks !!
Please also add Hackoctoberfest tag

**Comment by irshadmd** [comment]
go ahead 🚀
