### ISSUE TITLE
PsychoPod - psychology podcast proving website landing template.

### ISSUE THREAD

**Issue by priyanshi1282** [irshadmd/Awesome-CSS-Projects#137]
this website suggest the best psychology podcast. This is fully responsive website template.
Tech stack used - html, css, js.
screenshots : 
![image](https://user-images.githubusercontent.com/88632352/194033455-dede0e59-6dd2-44ba-a8a5-f2e2a12514a7.png)

pls consider this under hacktober22.

**Comment by irshadmd** [comment]
go ahead 🚀
