### ISSUE TITLE
Rock Paper Scissor Game

### ISSUE THREAD

**Issue by Keith-Web3** [irshadmd/Awesome-CSS-Projects#153]
A rock paper scissor game would be an awesome open source project. It would start as a small project for now but with time, the contributors to this repo can improve this drastically and make this a very fun game. The design is inspired by [frontendmentor rock paper scissor game](https://www.frontendmentor.io/challenges/rock-paper-scissors-game-pTgwgvgH)

**Comment by irshadmd** [comment]
looks good, we already have https://github.com/irshadmd/Awesome-CSS-Projects/tree/main/Rock%20Paper%20Scissors
you can improve it

**Comment by Keith-Web3** [comment]
Okay, I'll work on that
