### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by 0xSooki** [irshadmd/Awesome-CSS-Projects#16]
In order to avoid pushing unneccesary files eg. DS_Store, adding a .gitignore to the repo is recommended

**Comment by 0xSooki** [comment]
Would love to tackle this issue myself

**Comment by irshadmd** [comment]
yup go ahead 🚀

**Comment by yogesh-9999** [comment]
hey @irshadmd  please assign me this issue

**Comment by 0xSooki** [comment]
Will submit the PR shortly

**Comment by irshadmd** [comment]
> hey @irshadmd please assign me this issue

already assigned take something else
