### ISSUE TITLE
Add Color Game

### ISSUE THREAD

**Issue by incognion** [irshadmd/Awesome-CSS-Projects#174]
### About
  A cool and attractive Color guessing game that is made with HTML, CSS and Vanilla JavaScript.
### Features
- It generate a random RGB Color Combination, that have to be guessed by player that which color it'll generate. 
- It has three difficulty levels.
- The website is fully responsive on all devices.
- It has cool animations.

### Please assign it to me under Hacktoberfest 2022. Thank you.

**Comment by irshadmd** [comment]
go ahead 🚀
