### ISSUE TITLE
Add a Student grade calculator application

### ISSUE THREAD

**Issue by MohitNamdev22** [irshadmd/Awesome-CSS-Projects#192]
Can I add a Project in which the grade of a student can be calculated with the input of marks given?

**Comment by MohitNamdev22** [comment]
> Can you please assign this to me under Hacktoberfest label

Actually I've first found this issue and I'm working on this. You can make some other issue

**Comment by irshadmd** [comment]
go ahead @MohitNamdev22  🚀
