### ISSUE TITLE
Add a gym website

### ISSUE THREAD

**Issue by ravish036** [irshadmd/Awesome-CSS-Projects#197]
**TITLE**
Fitness Freak

**Description**
It is an website through which a person can register to access you facility. It contains all the description of the fitness plans, trainers etc...

**Screenshots**
![image](https://user-images.githubusercontent.com/84343005/194284720-843fbc81-14dc-4486-85f5-b7d1a28b9a57.png)
![image](https://user-images.githubusercontent.com/84343005/194284876-084e78f3-1c03-43cb-bbbb-4f07be7cd385.png)
![image](https://user-images.githubusercontent.com/84343005/194285024-66fe83f9-4717-4cc3-93cd-0b27c63ea02f.png)

I want to add this project in your repo under Hacktoberfest'22

**Comment by irshadmd** [comment]
go ahead 🚀
