### ISSUE TITLE
Will create a modern looking home page

### ISSUE THREAD

**Issue by BxtGeek** [irshadmd/Awesome-CSS-Projects#225]
Will create a modern looking home page

**Comment by irshadmd** [comment]
go ahead 🚀

**Comment by Aman-8955** [comment]
Hy, 
Can i work on this issue. I can make a good looking home page which will be show all projects. And I will link all projects on that home page then user can easily access all games from one place that is home page. 

I want to work on it. 
Can you assign me this issue. 
Thanks
