### ISSUE TITLE
Digital clock with date 

### ISSUE THREAD

**Issue by AbhiMishra-Now** [irshadmd/Awesome-CSS-Projects#23]
Digital clock with date ft. dark mode

**Comment by AbhiMishra-Now** [comment]
I'd like to work on that.

**Comment by irshadmd** [comment]
go ahead 🚀

**Comment by yogesh-9999** [comment]
hey @AbhiMishra-Now  please assign me this issue

**Comment by irshadmd** [comment]
> hey @AbhiMishra-Now please assign me this issue

already assigned
