### ISSUE TITLE
Invalid inputs handling

### ISSUE THREAD

**Issue by ronitsharma03** [irshadmd/Awesome-CSS-Projects#233]
![Screenshot from 2024-04-03 23-02-15](https://github.com/irshadmd/Awesome-CSS-Projects/assets/94978319/e4b4aa5c-8c37-4098-ae1f-0249c4a8e8e5)
When invalid city name is entered it should give a alert or notify user that entered city don't exists or wrong inputs

**Comment by irshadmd** [comment]
right, can also make it a dropdown list to select cities as you type

**Comment by ronitsharma03** [comment]
> right, can also make it a dropdown list to select cities as you type

@irshadmd yeah sure i'll definitely
