### ISSUE TITLE
Improvement of UI and fixing bugs

### ISSUE THREAD

**Issue by tanisha-salvi** [irshadmd/Awesome-CSS-Projects#36]
I can help improve the UI of the calculator page and fix a few bugs which appear while calculating the screen value. Kindly assign me this issue.

**Comment by irshadmd** [comment]
go ahead 🚀

**Comment by AyushSarode** [comment]
Can I improve UI?
Please assign me!

**Comment by irshadmd** [comment]
> Can I improve UI? Please assign me!

already assigned

**Comment by AyushSarode** [comment]
so can create pull request?

**Comment by irshadmd** [comment]
> so can create pull request for hacktoberfest without getting assign?

nope please create an issue first
