### ISSUE TITLE
Responsive City Landscape with Day/Night toggling.

### ISSUE THREAD

**Issue by yunsuklee** [irshadmd/Awesome-CSS-Projects#42]
Hey! I would like to add this project I did using only HTML and CSS. I made it responsive and interactive via media queries. Depending on screen size it will set background to day time or night!

![Screenshot from 2022-10-02 20-51-57](https://user-images.githubusercontent.com/92840840/193471074-8a239640-74c9-4134-af25-b7a228635118.png)
![Screenshot from 2022-10-02 20-52-08](https://user-images.githubusercontent.com/92840840/193471077-645057ed-e6d8-49e1-83b8-4eb26c762893.png)

**Comment by irshadmd** [comment]
go ahead 🚀
