### ISSUE TITLE
Tic-Tac-Toe

### ISSUE THREAD

**Issue by ZahraShahid** [irshadmd/Awesome-CSS-Projects#56]
I want to add a game Tic-Tac-Toe built using HTML, CSS, and JS.

**Comment by Shraddha16092002** [comment]
hey, I want to contribute to this repository by adding Tic-Tac-Toe game. Could you please assign this task to me

**Comment by irshadmd** [comment]
@ZahraShahid are you still working on this issue?

**Comment by Shraddha16092002** [comment]
heyy! If ZahraShahid is not working on this issue then could you please assign it to me?

**Comment by irshadmd** [comment]
sure @Shraddha16092002 

> heyy! If ZahraShahid is not working on this issue then could you please assign it to me?

**Comment by Shraddha16092002** [comment]
I have completed the task. Thank you
