### ISSUE TITLE
Spotify-Clone

### ISSUE THREAD

**Issue by Morbius00** [irshadmd/Awesome-CSS-Projects#60]
![Open Source Love](https://badges.frapsoft.com/os/v1/open-source.svg?v=103)

## SPOTIFY -CLONE
I want to create a Spotify Landing Page clone using this simple tech stacks :

<a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="40" height="40"/>   <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/> </a>   <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="javascript" width="30" height="30"/> </a>
Please assigned me for it #Hacktoberfest22

**Comment by Morbius00** [comment]
Please assigned me for it get pr in Hacktober fest 22

**Comment by irshadmd** [comment]
go ahead 🚀

**Comment by Rohitchaudhary13** [comment]
Hi @irshadmd , just created a PR on this issue, please check!

**Comment by Morbius00** [comment]
> Hi @irshadmd , just created a PR on this issue, please check!

hey @Rohitchaudhary13  I created the PR before you but due to some issues in the folder I have deleted it . But I don't think there is any problem because both the UI are different in our Projects

**Comment by Rohitchaudhary13** [comment]
there is no issue @Morbius00
