### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by drrav31** [irshadmd/Awesome-CSS-Projects#82]
I want to add a password generator which generates a strong random password of desired length

**Comment by irshadmd** [comment]
Go ahead 🚀

**Comment by Shaba1406** [comment]
Please assign this to me in the case if it remains unsolved.

**Comment by drrav31** [comment]
> @drrav31 are you still working?

Yeah. It'll be done today @irshadmd

**Comment by irshadmd** [comment]
> > @drrav31 are you still working?
> 
> Yeah. It'll be done today @irshadmd

great 👍🏻
