### ISSUE TITLE
The Simon Game

### ISSUE THREAD

**Issue by lordashuchauhan** [irshadmd/Awesome-CSS-Projects#86]
The game displays a series of tones and lights and requires a user to repeat the sequence by clicking on the blocks.
Using HTML, CSS & JAVASCRIPT,
@irshadmd please assign me this under HacktoberFest2022.

**Comment by irshadmd** [comment]
go ahead 🚀

**Comment by lordashuchauhan** [comment]
@irshadmd kindly review my PR #179

**Comment by lordashuchauhan** [comment]
@irshadmd kindly review my PR #211 , I have added the demo of the gameplay and gameover in GIF format.

**Comment by lordashuchauhan** [comment]
@irshadmd kindly preview my PR #213,
I have changed the demo folder to demo.gif
