### ISSUE TITLE
Discord Landing Page Clone

### ISSUE THREAD

**Issue by umeshchavda05** [irshadmd/Awesome-CSS-Projects#89]
I would like to make a discord landing page clone using CSS or Bootstrap for hacktoberfest

**Comment by umeshchavda05** [comment]
Please assign me this issue and add the hacktoberfest label

**Comment by yosaami** [comment]
hey @irshadmd, I have made this project before so I can contribute to it. please assign this to me. 
thanks.

**Comment by irshadmd** [comment]
go ahead @umeshchavda05
