### ISSUE TITLE
Day-night toggles

### ISSUE THREAD

**Issue by prjailani** [irshadmd/Awesome-CSS-Projects#9]
The toggle icon can change from the sun (during the day) to a moon (at night). If you like this idea please assign it to me. Thanks.

**Comment by irshadmd** [comment]
sure go ahead 🚀

**Comment by prjailani** [comment]
Hi, yes. I'll complete it within tonight.

**Comment by irshadmd** [comment]
okay no rush 👍🏻

> Hi, yes. I'll complete it within tonight.
